# Generated by Django 3.1.7 on 2021-09-28 13:45

import a_bank.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '1-Bank',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Done', 'Done')], default='pending', max_length=30)),
                ('store_path', models.CharField(blank=True, max_length=200)),
                ('processed_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bank', to='a_bank.bank')),
            ],
            options={
                'verbose_name': '2-Batch',
            },
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '3-File Types',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=a_bank.models.get_file_path, verbose_name='Document')),
                ('name', models.CharField(max_length=100)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_batch', to='a_bank.batch')),
                ('file_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_type_files', to='a_bank.filetypes')),
            ],
            options={
                'verbose_name': '4-File',
            },
        ),
    ]
