# Generated by Django 3.1.7 on 2021-10-23 22:09

import a_bank.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '1-Bank',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Done', 'Done')], default='pending', max_length=30)),
                ('number_files_submitted', models.IntegerField(blank=True, null=True)),
                ('store_path', models.CharField(blank=True, max_length=200)),
                ('processed_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bank', to='a_bank.bank')),
            ],
            options={
                'verbose_name': '2-Batch',
            },
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannual', 'Biannual')], default='', max_length=30)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '3-File Type',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=a_bank.models.get_file_path, verbose_name='File Path')),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('file_format', models.CharField(blank=True, max_length=100)),
                ('lastModified', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_batch', to='a_bank.batch')),
            ],
            options={
                'verbose_name': '4-File',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='file_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_types_bank', to='a_bank.filetypes'),
        ),
    ]
