# Generated by Django 3.1.7 on 2021-10-23 17:38

import a_bank.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ciiv', models.CharField(max_length=100, unique=True)),
                ('macro', models.CharField(blank=True, max_length=80)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('DP1', models.CharField(blank=True, max_length=250)),
                ('DP2', models.CharField(blank=True, max_length=250)),
                ('DP3', models.CharField(blank=True, max_length=250)),
                ('R1', models.CharField(blank=True, max_length=250)),
                ('R2', models.CharField(blank=True, max_length=250)),
                ('R3', models.CharField(blank=True, max_length=250)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '5- Activity',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '1-Bank',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Done', 'Done')], default='pending', max_length=30)),
                ('number_files_submitted', models.IntegerField(blank=True, null=True)),
                ('store_path', models.CharField(blank=True, max_length=200)),
                ('processed_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bank', to='a_bank.bank')),
            ],
            options={
                'verbose_name': '2-Batch',
            },
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannual', 'Biannual')], default='', max_length=30)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '3-File Type',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '9.2- Operation Type',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '9.3- Person Type',
            },
        ),
        migrations.CreateModel(
            name='PrecendentCrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '7- Crime',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '6- Risk',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '9.1- Service Type',
            },
        ),
        migrations.CreateModel(
            name='ReportBySuspicious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('avg_o_act_avg', models.BooleanField(default=False)),
                ('total_o_act_avg', models.BooleanField(default=False)),
                ('transactions', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicous_activity_type_batch', to='a_bank.activity')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_suspicous_activity_batch', to='a_bank.batch')),
            ],
            options={
                'verbose_name': '8.4- Report By Suspicous',
            },
        ),
        migrations.CreateModel(
            name='ReportByService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sercvice_type_batch', to='a_bank.batch')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_batch', to='a_bank.servicetype')),
            ],
            options={
                'verbose_name': '8.3- Report By Service',
            },
        ),
        migrations.CreateModel(
            name='ReportByPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=100)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_person_type_batch', to='a_bank.batch')),
                ('person_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_type_batch', to='a_bank.persontype')),
            ],
            options={
                'verbose_name': '8.2- Report by Person Type',
            },
        ),
        migrations.CreateModel(
            name='ReportByOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_operation_type_batch', to='a_bank.batch')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatioon_type_batch', to='a_bank.operationtype')),
            ],
            options={
                'verbose_name': '8.1- Report By Operations',
            },
        ),
        migrations.CreateModel(
            name='ReportByActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_activity_type_batch', to='a_bank.batch')),
                ('precendent_crime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precedent_crime_risk_type_batch', to='a_bank.precendentcrime')),
                ('risk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_batch', to='a_bank.risk')),
            ],
            options={
                'verbose_name': '8.0- Report Precedent Crime and Risk',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=a_bank.models.get_file_path, verbose_name='File Path')),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('file_format', models.CharField(blank=True, max_length=100)),
                ('lastModified', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_batch', to='a_bank.batch')),
            ],
            options={
                'verbose_name': '4-File',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='file_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_types_bank', to='a_bank.filetypes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='precedent_crime_ids',
            field=models.ManyToManyField(blank=True, to='a_bank.PrecendentCrime'),
        ),
        migrations.AddField(
            model_name='activity',
            name='risk_ids',
            field=models.ManyToManyField(blank=True, to='a_bank.Risk'),
        ),
    ]
