# Generated by Django 3.1.7 on 2021-10-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precendentcrime',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
