# Generated by Django 3.1.7 on 2021-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0002_batch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='store_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
