# Generated by Django 3.1.7 on 2021-10-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0002_auto_20211009_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
