# Generated by Django 3.1.7 on 2021-10-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0003_filetypes_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetypes',
            options={'verbose_name': '3-File Type'},
        ),
    ]
