# Generated by Django 3.1.7 on 2021-10-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0004_auto_20211009_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precendentcrime',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
