# Generated by Django 3.1.7 on 2021-10-09 19:21

import a_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0006_batch_file_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type_id',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to=a_bank.models.get_file_path, verbose_name='File Path'),
        ),
    ]
