# Generated by Django 3.1.7 on 2021-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0007_auto_20211009_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lastModified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
