# Generated by Django 3.1.7 on 2021-10-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0009_batch_number_files_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannual', 'Biannual')], default='', max_length=30),
        ),
    ]
