# Generated by Django 3.1.7 on 2021-10-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0010_filetypes_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypes',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('biannual', 'Biannual')], default='', max_length=30),
        ),
    ]
