# Generated by Django 3.1.7 on 2021-10-10 00:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0011_auto_20211009_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportByActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_activity_type_batch', to='a_bank.batch')),
                ('precendent_crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedent_crime_risk_type_batch', to='a_bank.precendentcrime')),
                ('risk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_batch', to='a_bank.risk')),
            ],
            options={
                'verbose_name': '8- Precedent Crime and Risk',
            },
        ),
    ]
