# Generated by Django 3.1.7 on 2021-10-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0012_reportbyactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportbyactivity',
            options={'verbose_name': '8- Report Precedent Crime and Risk'},
        ),
        migrations.RemoveField(
            model_name='reportbyactivity',
            name='name',
        ),
    ]
