# Generated by Django 3.1.7 on 2021-10-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0014_auto_20211010_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbyactivity',
            name='risk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_batch', to='a_bank.risk'),
        ),
    ]
