# Generated by Django 3.1.7 on 2021-10-10 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0015_auto_20211010_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '9- Operation Type',
            },
        ),
        migrations.CreateModel(
            name='ReportByOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_operation_type_batch', to='a_bank.batch')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatioon_type_batch', to='a_bank.operationtype')),
            ],
            options={
                'verbose_name': '10- Report By Operations',
            },
        ),
    ]
