# Generated by Django 3.1.7 on 2021-10-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0016_operationtype_reportbyoperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportbyoperation',
            options={'verbose_name': '8.1- Report By Operations'},
        ),
    ]
