# Generated by Django 3.1.7 on 2021-10-10 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0017_auto_20211010_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '11- Person Type',
            },
        ),
        migrations.CreateModel(
            name='ReportByPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_person_type_batch', to='a_bank.batch')),
                ('person_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_type_batch', to='a_bank.persontype')),
            ],
            options={
                'verbose_name': '8.2- Report by Person Type',
            },
        ),
    ]
