# Generated by Django 3.1.7 on 2021-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0018_persontype_reportbyperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbyperson',
            name='risk',
            field=models.CharField(max_length=100),
        ),
    ]
