# Generated by Django 3.1.7 on 2021-10-10 02:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0019_auto_20211010_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '11- Service Type',
            },
        ),
        migrations.AlterModelOptions(
            name='reportbyactivity',
            options={'verbose_name': '8.0- Report Precedent Crime and Risk'},
        ),
        migrations.CreateModel(
            name='ReportByService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sercvice_type_batch', to='a_bank.batch')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_batch', to='a_bank.servicetype')),
            ],
            options={
                'verbose_name': '8.3- Report By Service',
            },
        ),
    ]
