# Generated by Django 3.1.7 on 2021-10-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0020_auto_20211010_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbyservice',
            name='phase',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
