# Generated by Django 3.1.7 on 2021-10-10 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0021_auto_20211010_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': '9.2- Operation Type'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'verbose_name': '9.3- Person Type'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': '9.1- Service Type'},
        ),
        migrations.CreateModel(
            name='ReportBySuspicious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('avg_o_act_avg', models.BooleanField(default=False)),
                ('total_o_act_avg', models.BooleanField(default=False)),
                ('transactions', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicous_activity_type_batch', to='a_bank.activity')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_suspicous_activity_batch', to='a_bank.batch')),
            ],
            options={
                'verbose_name': '8.4- Report By Service',
            },
        ),
    ]
