# Generated by Django 3.1.7 on 2021-10-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_bank', '0022_auto_20211010_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportbysuspicious',
            options={'verbose_name': '8.4- Report By Suspicous'},
        ),
    ]
