# Generated by Django 3.1.7 on 2021-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_report', '0002_auto_20211023_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'R1- Activity Types'},
        ),
        migrations.AlterModelOptions(
            name='precendentcrime',
            options={'verbose_name': 'R3- Crime Types'},
        ),
        migrations.AlterModelOptions(
            name='reportbyactivity',
            options={'verbose_name': '8.0- Report By Activity'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name': 'R2- Risk Types'},
        ),
        migrations.AddField(
            model_name='activity',
            name='DP1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='DP2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='DP3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='R1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='R2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='R3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
