# Generated by Django 3.1.7 on 2021-10-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_report', '0003_auto_20211024_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbyactivity',
            name='activity_id',
        ),
    ]
